from till_scrapers.base import BaseScraper


class BofaScraper(BaseScraper):
    """Bank of America scraper — generated by `till scaffold`."""

    LOGIN_URL = "https://www.bankofamerica.com/"

    async def extract(self, page) -> dict:
        # TODO: implement extraction
        await page.screenshot(path="/tmp/till_bofa_debug.png")

        return {
            "status": "ok",
            "source": "bofa",
            "accounts": [],
            "transactions": [],
            "positions": [],
            "balance_history": [],
        }
