from till_scrapers.base import BaseScraper


class FidelityScraper(BaseScraper):
    """Fidelity scraper — generated by `till scaffold`."""

    LOGIN_URL = "https://digital.fidelity.com/prgw/digital/login/full-page"

    async def extract(self, page) -> dict:
        # TODO: implement extraction
        await page.screenshot(path="/tmp/till_fidelity_debug.png")

        return {
            "status": "ok",
            "source": "fidelity",
            "accounts": [],
            "transactions": [],
            "positions": [],
            "balance_history": [],
        }
