from till_scrapers.base import BaseScraper


class AmexScraper(BaseScraper):
    """American Express scraper — generated by `till scaffold`."""

    LOGIN_URL = "https://www.americanexpress.com/en-us/account/login"

    async def extract(self, page) -> dict:
        # TODO: implement extraction
        await page.screenshot(path="/tmp/till_amex_debug.png")

        return {
            "status": "ok",
            "source": "amex",
            "accounts": [],
            "transactions": [],
            "positions": [],
            "balance_history": [],
        }
