from till_scrapers.base import BaseScraper


class WellsfargoScraper(BaseScraper):
    """Wells Fargo scraper — generated by `till scaffold`."""

    LOGIN_URL = "https://connect.secure.wellsfargo.com/auth/login/present"

    async def extract(self, page) -> dict:
        # TODO: implement extraction
        await page.screenshot(path="/tmp/till_wellsfargo_debug.png")

        return {
            "status": "ok",
            "source": "wellsfargo",
            "accounts": [],
            "transactions": [],
            "positions": [],
            "balance_history": [],
        }
