import os
from till_scrapers.base import BaseScraper


class MorganstanleyScraper(BaseScraper):
    """Morgan Stanley scraper — generated by `till scaffold`.

    Supports both personal accounts and workplace/StockPlan Connect.
    Set TILL_MORGANSTANLEY_VARIANT=workplace for employer accounts.
    """

    LOGIN_URL = "https://login.morganstanley.com/SignIn/"

    def __init__(self, headless: bool = True):
        super().__init__(headless=False)  # MS detects headless
        self.variant = os.environ.get("TILL_MORGANSTANLEY_VARIANT", "personal")

    async def extract(self, page) -> dict:
        # TODO: implement extraction
        # Use self.variant to distinguish personal vs workplace
        await page.screenshot(path="/tmp/till_morganstanley_debug.png")

        return {
            "status": "ok",
            "source": "morganstanley",
            "accounts": [],
            "transactions": [],
            "positions": [],
            "balance_history": [],
        }
